model_version: v5
model_edit: 06
model_run: B
model_desc: "Remove Batch. New Dataset"
dataset: LIDARDataGen_FRCPowerUp_03_A
learning_rate: 0.02
batch_size: 32
epoch: 50
conv1_filter: 16
conv2_filter: 32
conv3_filter: 64
# conv4_filter: 128
conv1_kernal: 7
conv2_kernal: 5
conv3_kernal: 3
# conv4_kernal: 3
fully_connected: 128
load: False
