model_version: v5
model_edit: 05
model_run: C
model_desc: "Higher Batch Size. (Score beating)"
dataset: LIDARDataGen_FRCPowerUp_02_B
learning_rate: 0.025
batch_size: 128
epoch: 75
conv1_filter: 16
conv2_filter: 32
conv3_filter: 64
conv1_kernal: 7
conv2_kernal: 5
conv3_kernal: 3
fully_connected: 128
load: False
