model_version: v5
model_edit: 04
model_run: B
model_desc: "Higher Learning Rate."
dataset: LIDARDataGen_FRCPowerUp_01_D
learning_rate: 0.05
batch_size: 32
epoch: 30
conv1_filter: 16
conv2_filter: 32
conv3_filter: 64
conv1_kernal: 7
conv2_kernal: 5
conv3_kernal: 3
fully_connected: 128
load: False
