model_version: testing
model_edit: 01
model_run: A
model_desc: "More Training Data. higher filter size."
dataset: LIDARDataGen_FRCPowerUp_01_B
learning_rate: 0.01
batch_size: 32
epoch: 30
conv1_filter: 16
conv2_filter: 32
conv1_kernal: 8
conv2_kernal: 4
fully_connected: 128
load: False
