model_version: testing
model_edit: 01
model_run: A
model_desc: "RNN Development"
dataset: LIDARDataGen_Debug_01
learning_rate: 0.01
batch_size: 32
epoch: 30
conv1_filter: 16
conv2_filter: 32
conv3_filter: 64
conv1_kernal: 7
conv2_kernal: 5
conv3_kernal: 3
fully_connected: 128
load: False
